// Code generated by mockery v2.40.1. DO NOT EDIT.

package mocks

import (
	domain "github.com/dmitrii-a/image-previewer/internal/domain"
	mock "github.com/stretchr/testify/mock"
)

// ImageRepository is an autogenerated mock type for the ImageRepository type
type ImageRepository struct {
	mock.Mock
}

// Get provides a mock function with given fields: url, width, height
func (_m *ImageRepository) Get(url string, width int, height int) (*domain.Image, error) {
	ret := _m.Called(url, width, height)

	if len(ret) == 0 {
		panic("no return value specified for Get")
	}

	var r0 *domain.Image

	var r1 error

	if rf, ok := ret.Get(0).(func(string, int, int) (*domain.Image, error)); ok {
		return rf(url, width, height)
	}

	if rf, ok := ret.Get(0).(func(string, int, int) *domain.Image); ok {
		r0 = rf(url, width, height)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*domain.Image)
		}
	}

	if rf, ok := ret.Get(1).(func(string, int, int) error); ok {
		r1 = rf(url, width, height)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// Save provides a mock function with given fields: image
func (_m *ImageRepository) Save(image *domain.Image) error {
	ret := _m.Called(image)

	if len(ret) == 0 {
		panic("no return value specified for Save")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*domain.Image) error); ok {
		r0 = rf(image)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewImageRepository creates a new instance of ImageRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewImageRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *ImageRepository {
	mock := &ImageRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
